[workspace]
resolver = "2"
members = []

[workspace.package]
version = "0.0.0"
edition = "2021"
authors = ["Romain Failla <rigbuntu@gmail.com>"]
license = "MIT OR Apache-2.0"

[workspace.dependencies]
